apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: servicebus
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: persistent-claim
      size: 8Gi
      class: ssd-retain
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 8Gi
      class: ssd-retain
  entityOperator:
    topicOperator: {}
    userOperator: {}
