apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: kafka-servicebus-staging
spec:
  keycloak: keycloak-jx-production
  realm: dev
  clientId: kafka-staging
  clientType: confidential
  directAccessGrantsEnabled: true
  standardFlowEnabled: false
  implicitFlowEnabled: false
  serviceAccountsEnabled: true
  mapper:
    - name: audience
      protocolMapper: oidc-audience-mapper
      config:
        claim.name: audience
        access.token.claim: "true"
        included.client.audience: {{ template "keycloakclient" . }}
    - name: username
      protocolMapper: oidc-usermodel-property-mapper
      config:
        access.token.claim: "true"
        claim.name: username
        jsonType.label: String
        user.attribute: username
    - name: clientRoles
      protocolMapper: oidc-usermodel-client-role-mapper
      config:
        access.token.claim: "true"
        claim.name: clientRoles
        jsonType.label: String
        multivalued: "true"
    - name: roles
      protocolMapper: oidc-usermodel-realm-role-mapper
      config:
        access.token.claim: "true"
        claim.name: roles
        jsonType.label: String
        multivalued: "true"
