apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql
spec:
  teamId: "staging"
  volume:
    size: 8Gi
    storageClass: ssd-retain
  numberOfInstances: 5
  users:
    cldntvadmin:  # database owner
    - superuser
    - createdb
  preparedDatabases:
    keycloak: {}
  postgresql:
    version: "12"