apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 8Gi
    storageClass: ssd-retain
  numberOfInstances: 5
  users:
    cldntvadmin:  # database owner
    - superuser
    - createdb
    keycloak:
    - admin
  databases:
    keycloak: keycloak  # dbname: owner
  postgresql:
    version: "12"