apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: staging-postgresql
spec:
  teamId: "staging"
  volume:
    size: 20Gi
    storageClass: ssd
  numberOfInstances: 3
  users:
    cldntvadmin:  # database owner
    - superuser
    - createdb
    keycloak:
  databases:
    keycloak: keycloak
  postgresql:
    version: "12"
