apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
stringData:
  adminPassword: {{ required "postgresAdminPassword is required." .Values.postgresAdminPassword }}
  adminUsername: {{ required "postgresAdminUsername is required." .Values.postgresAdminUsername }}
type: Opaque
