apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: staging-postgresql
spec:
  teamId: "staging"
  volume:
    size: 8Gi
    storageClass: ssd-retain
  numberOfInstances: 5
  users:
    cldntvadmin:  # database owner
    - superuser
    - createdb
  databases:
    keycloak: keycloak_owner
  preparedDatabases:
    keycloak:
      schemas:
        my_existing_schema: {}
  postgresql:
    version: "12"