apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: monitor
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  replicas: 1
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: web

---

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
    name: monitor
    namespace: monitoring
spec:
    replicas: 1
    securityContext: {}