apiVersion: v1
kind: Secret
metadata:
  name: sourced-db
stringData:
  user: {{ required "sourced.user is required." .Values.sourced.user }}
  password: {{ required "sourced.password is required." .Values.sourced.password }}
type: Opaque
