dependencies:
- name: auth
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.55
- name: content
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.37
- name: demo-app
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.11
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: www
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.25
- name: mongodb-replicaset
  version: 3.15.1
  repository: https://kubernetes-charts.storage.googleapis.com/
