dependencies:
- name: auth
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.44
- name: content
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.28
- name: demo-app
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.10
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: www
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.19
