dependencies:
- name: auth
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.56
- name: content
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.40
- name: demo-app
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.14
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 3.15.1
- name: person-model
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.20
- name: www
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.26
