dependencies:
- name: auth
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.54
- name: content
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.37
- name: demo-app
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.11
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: postgresql-ha
  repository: https://charts.bitnami.com/bitnami
  version: 3.2.3
- name: www
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.25
