PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbHost: staging-postgresql.jx-staging.svc.cluster.local
        dbName: keycloak
        dbVendor: postgres
        existingSecret: keycloak.staging-postgresql.credentials.postgresql.acid.zalan.do
        existingSecretPasswordKey: password
        existingSecretUsernameKey: username
      replicas: 3
      username: vault:staging/auth/keycloak:adminUsername
  keycloakAdminPassword: vault:staging/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:staging/auth/keycloak:adminUsername
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
content:
  cors:
    origin: cloudnativeentrepreneur.dev
  keycloak:
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.dev
      includeNamespace: true
      serviceName: content
  session:
    key: vault:staging/auth/session:key
demo-app:
  keycloak:
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.dev
      includeNamespace: true
      serviceName: demo-app
domain: cloudnativeentrepreneur.dev
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.dev
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-dev-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
mongodb-replicaset:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - mongodb-replicaset
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mongodb-replicaset
        topologyKey: kubernetes.io/hostname
  auth:
    adminPassword: vault:staging/mongodb:adminPassword
    adminUser: vault:staging/mongodb:adminUser
    enabled: true
    key: vault:staging/mongodb:key
    metricsPassword: vault:staging/mongodb:metricsPassword
    metricsUser: vault:staging/mongodb:metricsUser
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: ssd-retain
  podDisruptionBudget:
    minAvailable: 2
prow: {}
sourced:
  password: vault:staging/mongodb:sourcedPassword
  user: vault:staging/mongodb:sourcedUser
www:
  env:
    SAPPER_CLIENT_CONTENT_GRAPHQL_URL: https://content-jx-staging.cloudnativeentrepreneur.dev/graphql
    SAPPER_SERVER_CONTENT_GRAPHQL_URL: http://content.jx-staging.svc.cluster.local/graphql
  keycloak:
    redirectUris:
      allowAll: false
      allowLocalhost: true
      domain: cloudnativeentrepreneur.dev
      includeNamespace: true
      serviceName: www
  session:
    key: vault:staging/auth/session:key
