PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.dev
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-dev-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
auth:
  postgresAdminPassword: vault:staging/auth/postgres:adminPassword
  postgresAdminUsername: vault:staging/auth/postgres:adminUsername
  keycloakAdminPassword: vault:staging/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:staging/auth/keycloak:adminUsername
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      username: vault:staging/auth/postgres:adminUsername
      persistence:
        dbHost: jx-postgresql-ha-postgresql.{{ .Release.Namespace }}.svc.cluster.local
        existingSecret: auth-postgres
        existingSecretPasswordKey: adminPassword
        existingSecretUsernameKey: adminUsername
  postgresql-ha:
    global:
      postgresql:
        username: vault:staging/auth/postgres:adminUsername
        password: vault:staging/auth/postgres:adminPassword
        repmgrUsername: vault:staging/auth/postgres:repmgrUsername
        repmgrPassword: vault:staging/auth/postgres:repmgrPassword
        database: keycloak
      pgpool:
        adminUsername: vault:staging/auth/postgres:pgpoolAdminUsername
        adminPassword: vault:staging/auth/postgres:pgpoolAdminPassword
