PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbHost: staging-postgresql.jx-staging.svc.cluster.local
        dbName: keycloak
        dbVendor: postgres
        existingSecret: keycloak.staging-postgresql.credentials.postgresql.acid.zalan.do
        existingSecretPasswordKey: password
        existingSecretUsernameKey: username
      username: vault:staging/auth/keycloak:adminUsername
  keycloakAdminPassword: vault:staging/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:staging/auth/keycloak:adminUsername
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
demo-app:
  keycloak:
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.dev
      includeNamespace: true
      serviceName: demo-app
domain: cloudnativeentrepreneur.dev
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.dev
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-dev-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
mongodb-replicaset:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - mongodb-replicaset
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                    - mongodb-replicaset
            topologyKey: failure-domain.beta.kubernetes.io/zone
  auth:
    enabled: true
    adminUser: vault:staging/mongodb:adminUser
    adminPassword: vault:staging/mongodb:adminPassword
    metricsUser: vault:staging/mongodb:metricsUser
    metricsPassword: vault:staging/mongodb:metricsPassword
  persistentVolume:
    enabled: true
    storageClass: ssd-retain
    size: 10Gi
  podDisruptionBudget:
    minAvailable: 2