PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.dev
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-dev-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
auth:
  postgresAdminPassword: vault:staging/auth/postgres:password
  postgresAdminUser: vault:staging/auth/postgres:user
  keycloakAdminPassword: vault:staging/auth/keycloak:password
  keycloakAdminUser: vault:staging/auth/keycloak:user
  keycloak:
    existingSecret: auth-keycloak
    username: vault:staging/auth/postgres:user
    persistence:
      existingSecret: auth-postgres
      existingSecretPasswordKey: password
      existingSecretUsernameKey: user